#######################################################################################################################
# Copyright (C) 2016  Regents of the University of California
#
# This is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License (GNU GPL) as published by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GNU General Public License can be found in LICENSE.TXT in the root of the source code repository.
# Additionally, it can be found at http://www.gnu.org/licenses/.
#
# NOTES: Per GNU GPLv3 terms:
#   * This notice must be kept in this source file
#   * Changes to the source must be clearly noted with date & time of change
#
# If you use this software in a product, an explicit acknowledgment in the product documentation of the contribution
# by Project IDA, Institute of Geophysics and Planetary Physics, UCSD would be appreciated but is not required.
#######################################################################################################################

"""GUI Python code auto-generated from Qt Creator *.ui files by PyQt pyuic utility."""
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditDlg(object):
    def setupUi(self, EditDlg):
        EditDlg.setObjectName("EditDlg")
        EditDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        EditDlg.resize(720, 380)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditDlg.sizePolicy().hasHeightForWidth())
        EditDlg.setSizePolicy(sizePolicy)
        EditDlg.setMinimumSize(QtCore.QSize(720, 380))
        EditDlg.setMaximumSize(QtCore.QSize(720, 380))
        EditDlg.setMouseTracking(False)
        EditDlg.setFocusPolicy(QtCore.Qt.WheelFocus)
        EditDlg.setModal(True)
        self.mainGB = QtWidgets.QGroupBox(EditDlg)
        self.mainGB.setGeometry(QtCore.QRect(15, 10, 691, 331))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mainGB.setFont(font)
        self.mainGB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.mainGB.setObjectName("mainGB")
        self.sensorBGB = QtWidgets.QGroupBox(self.mainGB)
        self.sensorBGB.setGeometry(QtCore.QRect(330, 191, 351, 131))
        self.sensorBGB.setTitle("")
        self.sensorBGB.setObjectName("sensorBGB")
        self.label_28 = QtWidgets.QLabel(self.sensorBGB)
        self.label_28.setGeometry(QtCore.QRect(7, 5, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_10 = QtWidgets.QLabel(self.sensorBGB)
        self.label_10.setGeometry(QtCore.QRect(70, 26, 42, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.sensBMonPortLE = QtWidgets.QLineEdit(self.sensorBGB)
        self.sensBMonPortLE.setGeometry(QtCore.QRect(122, 52, 50, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensBMonPortLE.sizePolicy().hasHeightForWidth())
        self.sensBMonPortLE.setSizePolicy(sizePolicy)
        self.sensBMonPortLE.setMinimumSize(QtCore.QSize(50, 0))
        self.sensBMonPortLE.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sensBMonPortLE.setFont(font)
        self.sensBMonPortLE.setFrame(False)
        self.sensBMonPortLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.sensBMonPortLE.setObjectName("sensBMonPortLE")
        self.label_14 = QtWidgets.QLabel(self.sensorBGB)
        self.label_14.setGeometry(QtCore.QRect(10, 52, 102, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(102, 0))
        self.label_14.setMaximumSize(QtCore.QSize(102, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.sensBCB = QtWidgets.QComboBox(self.sensorBGB)
        self.sensBCB.setGeometry(QtCore.QRect(117, 22, 231, 26))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.sensBCB.setFont(font)
        self.sensBCB.setObjectName("sensBCB")
        self.sensBLocLE = QtWidgets.QLineEdit(self.sensorBGB)
        self.sensBLocLE.setGeometry(QtCore.QRect(122, 77, 50, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensBLocLE.sizePolicy().hasHeightForWidth())
        self.sensBLocLE.setSizePolicy(sizePolicy)
        self.sensBLocLE.setMinimumSize(QtCore.QSize(50, 0))
        self.sensBLocLE.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sensBLocLE.setFont(font)
        self.sensBLocLE.setText("")
        self.sensBLocLE.setFrame(False)
        self.sensBLocLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.sensBLocLE.setObjectName("sensBLocLE")
        self.label_8 = QtWidgets.QLabel(self.sensorBGB)
        self.label_8.setGeometry(QtCore.QRect(10, 77, 102, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(102, 0))
        self.label_8.setMaximumSize(QtCore.QSize(102, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.sensBPriChnsLE = QtWidgets.QLineEdit(self.sensorBGB)
        self.sensBPriChnsLE.setGeometry(QtCore.QRect(122, 102, 125, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensBPriChnsLE.sizePolicy().hasHeightForWidth())
        self.sensBPriChnsLE.setSizePolicy(sizePolicy)
        self.sensBPriChnsLE.setMinimumSize(QtCore.QSize(125, 0))
        self.sensBPriChnsLE.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sensBPriChnsLE.setFont(font)
        self.sensBPriChnsLE.setFrame(False)
        self.sensBPriChnsLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.sensBPriChnsLE.setObjectName("sensBPriChnsLE")
        self.label_9 = QtWidgets.QLabel(self.sensorBGB)
        self.label_9.setGeometry(QtCore.QRect(10, 103, 102, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(102, 0))
        self.label_9.setMaximumSize(QtCore.QSize(102, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.sensorAGB = QtWidgets.QGroupBox(self.mainGB)
        self.sensorAGB.setGeometry(QtCore.QRect(330, 40, 351, 131))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sensorAGB.setFont(font)
        self.sensorAGB.setTitle("")
        self.sensorAGB.setObjectName("sensorAGB")
        self.label = QtWidgets.QLabel(self.sensorAGB)
        self.label.setGeometry(QtCore.QRect(70, 27, 42, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.sensorAGB)
        self.label_2.setGeometry(QtCore.QRect(10, 54, 102, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(102, 0))
        self.label_2.setMaximumSize(QtCore.QSize(102, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.sensAMonPortLE = QtWidgets.QLineEdit(self.sensorAGB)
        self.sensAMonPortLE.setGeometry(QtCore.QRect(122, 53, 50, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensAMonPortLE.sizePolicy().hasHeightForWidth())
        self.sensAMonPortLE.setSizePolicy(sizePolicy)
        self.sensAMonPortLE.setMinimumSize(QtCore.QSize(50, 0))
        self.sensAMonPortLE.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sensAMonPortLE.setFont(font)
        self.sensAMonPortLE.setFrame(False)
        self.sensAMonPortLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.sensAMonPortLE.setObjectName("sensAMonPortLE")
        self.label_27 = QtWidgets.QLabel(self.sensorAGB)
        self.label_27.setGeometry(QtCore.QRect(7, 5, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.sensACB = QtWidgets.QComboBox(self.sensorAGB)
        self.sensACB.setGeometry(QtCore.QRect(117, 23, 231, 26))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sensACB.setFont(font)
        self.sensACB.setObjectName("sensACB")
        self.sensALocLE = QtWidgets.QLineEdit(self.sensorAGB)
        self.sensALocLE.setGeometry(QtCore.QRect(122, 79, 50, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensALocLE.sizePolicy().hasHeightForWidth())
        self.sensALocLE.setSizePolicy(sizePolicy)
        self.sensALocLE.setMinimumSize(QtCore.QSize(50, 0))
        self.sensALocLE.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sensALocLE.setFont(font)
        self.sensALocLE.setText("")
        self.sensALocLE.setFrame(False)
        self.sensALocLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.sensALocLE.setObjectName("sensALocLE")
        self.label_3 = QtWidgets.QLabel(self.sensorAGB)
        self.label_3.setGeometry(QtCore.QRect(10, 79, 102, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(102, 0))
        self.label_3.setMaximumSize(QtCore.QSize(102, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.sensAPriChnsLE = QtWidgets.QLineEdit(self.sensorAGB)
        self.sensAPriChnsLE.setGeometry(QtCore.QRect(122, 105, 125, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensAPriChnsLE.sizePolicy().hasHeightForWidth())
        self.sensAPriChnsLE.setSizePolicy(sizePolicy)
        self.sensAPriChnsLE.setMinimumSize(QtCore.QSize(125, 0))
        self.sensAPriChnsLE.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sensAPriChnsLE.setFont(font)
        self.sensAPriChnsLE.setFrame(False)
        self.sensAPriChnsLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.sensAPriChnsLE.setObjectName("sensAPriChnsLE")
        self.label_4 = QtWidgets.QLabel(self.sensorAGB)
        self.label_4.setGeometry(QtCore.QRect(10, 106, 102, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(102, 0))
        self.label_4.setMaximumSize(QtCore.QSize(102, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.q330GB = QtWidgets.QGroupBox(self.mainGB)
        self.q330GB.setGeometry(QtCore.QRect(10, 40, 310, 281))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.q330GB.setFont(font)
        self.q330GB.setTitle("")
        self.q330GB.setObjectName("q330GB")
        self.label_26 = QtWidgets.QLabel(self.q330GB)
        self.label_26.setGeometry(QtCore.QRect(9, 5, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_5 = QtWidgets.QLabel(self.q330GB)
        self.label_5.setGeometry(QtCore.QRect(94, 59, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.staLE = QtWidgets.QLineEdit(self.q330GB)
        self.staLE.setGeometry(QtCore.QRect(145, 59, 60, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.staLE.sizePolicy().hasHeightForWidth())
        self.staLE.setSizePolicy(sizePolicy)
        self.staLE.setMinimumSize(QtCore.QSize(60, 0))
        self.staLE.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.staLE.setFont(font)
        self.staLE.setFrame(False)
        self.staLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.staLE.setObjectName("staLE")
        self.label_6 = QtWidgets.QLabel(self.q330GB)
        self.label_6.setGeometry(QtCore.QRect(64, 87, 77, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.networkLabel = QtWidgets.QLabel(self.q330GB)
        self.networkLabel.setGeometry(QtCore.QRect(85, 31, 56, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.networkLabel.setFont(font)
        self.networkLabel.setObjectName("networkLabel")
        self.netLE = QtWidgets.QLineEdit(self.q330GB)
        self.netLE.setGeometry(QtCore.QRect(145, 31, 40, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.netLE.sizePolicy().hasHeightForWidth())
        self.netLE.setSizePolicy(sizePolicy)
        self.netLE.setMinimumSize(QtCore.QSize(40, 0))
        self.netLE.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.netLE.setFont(font)
        self.netLE.setFrame(False)
        self.netLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.netLE.setObjectName("netLE")
        self.ipLE = QtWidgets.QLineEdit(self.q330GB)
        self.ipLE.setGeometry(QtCore.QRect(145, 87, 160, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ipLE.sizePolicy().hasHeightForWidth())
        self.ipLE.setSizePolicy(sizePolicy)
        self.ipLE.setMinimumSize(QtCore.QSize(160, 0))
        self.ipLE.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ipLE.setFont(font)
        self.ipLE.setFrame(False)
        self.ipLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.ipLE.setObjectName("ipLE")
        self.label_12 = QtWidgets.QLabel(self.q330GB)
        self.label_12.setGeometry(QtCore.QRect(79, 171, 62, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.dpLE = QtWidgets.QLineEdit(self.q330GB)
        self.dpLE.setGeometry(QtCore.QRect(145, 171, 60, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpLE.sizePolicy().hasHeightForWidth())
        self.dpLE.setSizePolicy(sizePolicy)
        self.dpLE.setMinimumSize(QtCore.QSize(60, 0))
        self.dpLE.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dpLE.setFont(font)
        self.dpLE.setText("")
        self.dpLE.setFrame(False)
        self.dpLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.dpLE.setObjectName("dpLE")
        self.snLE = QtWidgets.QLineEdit(self.q330GB)
        self.snLE.setGeometry(QtCore.QRect(145, 143, 160, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snLE.sizePolicy().hasHeightForWidth())
        self.snLE.setSizePolicy(sizePolicy)
        self.snLE.setMinimumSize(QtCore.QSize(160, 0))
        self.snLE.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.snLE.setFont(font)
        self.snLE.setFrame(False)
        self.snLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.snLE.setObjectName("snLE")
        self.label_11 = QtWidgets.QLabel(self.q330GB)
        self.label_11.setGeometry(QtCore.QRect(96, 143, 45, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.tagnoLE = QtWidgets.QLineEdit(self.q330GB)
        self.tagnoLE.setGeometry(QtCore.QRect(145, 115, 60, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagnoLE.sizePolicy().hasHeightForWidth())
        self.tagnoLE.setSizePolicy(sizePolicy)
        self.tagnoLE.setMinimumSize(QtCore.QSize(60, 0))
        self.tagnoLE.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tagnoLE.setFont(font)
        self.tagnoLE.setFrame(False)
        self.tagnoLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.tagnoLE.setObjectName("tagnoLE")
        self.label_7 = QtWidgets.QLabel(self.q330GB)
        self.label_7.setGeometry(QtCore.QRect(105, 115, 36, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_13 = QtWidgets.QLabel(self.q330GB)
        self.label_13.setGeometry(QtCore.QRect(11, 199, 130, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.dpauthLE = QtWidgets.QLineEdit(self.q330GB)
        self.dpauthLE.setGeometry(QtCore.QRect(145, 199, 60, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpauthLE.sizePolicy().hasHeightForWidth())
        self.dpauthLE.setSizePolicy(sizePolicy)
        self.dpauthLE.setMinimumSize(QtCore.QSize(60, 0))
        self.dpauthLE.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dpauthLE.setFont(font)
        self.dpauthLE.setFrame(False)
        self.dpauthLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.dpauthLE.setObjectName("dpauthLE")
        self.saveBtn = QtWidgets.QPushButton(EditDlg)
        self.saveBtn.setGeometry(QtCore.QRect(633, 346, 81, 32))
        self.saveBtn.setObjectName("saveBtn")
        self.cancelBtn = QtWidgets.QPushButton(EditDlg)
        self.cancelBtn.setGeometry(QtCore.QRect(550, 346, 81, 32))
        self.cancelBtn.setObjectName("cancelBtn")
        self.resetBtn = QtWidgets.QPushButton(EditDlg)
        self.resetBtn.setGeometry(QtCore.QRect(10, 346, 81, 32))
        self.resetBtn.setObjectName("resetBtn")

        self.retranslateUi(EditDlg)
        QtCore.QMetaObject.connectSlotsByName(EditDlg)
        EditDlg.setTabOrder(self.netLE, self.staLE)
        EditDlg.setTabOrder(self.staLE, self.ipLE)
        EditDlg.setTabOrder(self.ipLE, self.tagnoLE)
        EditDlg.setTabOrder(self.tagnoLE, self.snLE)
        EditDlg.setTabOrder(self.snLE, self.dpLE)
        EditDlg.setTabOrder(self.dpLE, self.dpauthLE)
        EditDlg.setTabOrder(self.dpauthLE, self.sensACB)
        EditDlg.setTabOrder(self.sensACB, self.sensAMonPortLE)
        EditDlg.setTabOrder(self.sensAMonPortLE, self.sensALocLE)
        EditDlg.setTabOrder(self.sensALocLE, self.sensAPriChnsLE)
        EditDlg.setTabOrder(self.sensAPriChnsLE, self.sensBCB)
        EditDlg.setTabOrder(self.sensBCB, self.sensBMonPortLE)
        EditDlg.setTabOrder(self.sensBMonPortLE, self.sensBLocLE)
        EditDlg.setTabOrder(self.sensBLocLE, self.sensBPriChnsLE)
        EditDlg.setTabOrder(self.sensBPriChnsLE, self.cancelBtn)
        EditDlg.setTabOrder(self.cancelBtn, self.saveBtn)
        EditDlg.setTabOrder(self.saveBtn, self.resetBtn)

    def retranslateUi(self, EditDlg):
        _translate = QtCore.QCoreApplication.translate
        EditDlg.setWindowTitle(_translate("EditDlg", "Dialog"))
        self.mainGB.setTitle(_translate("EditDlg", "Edit Calibration Configuration"))
        self.label_28.setText(_translate("EditDlg", "Sensor B"))
        self.label_10.setToolTip(_translate("EditDlg", "<html><head/><body><p>Sensor Model.</p></body></html>"))
        self.label_10.setText(_translate("EditDlg", "Model:"))
        self.sensBMonPortLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>Calibration monitoring channel for sensor B</p></body></html>"))
        self.sensBMonPortLE.setPlaceholderText(_translate("EditDlg", "[1-3]"))
        self.label_14.setToolTip(_translate("EditDlg", "<html><head/><body><p>Calibration Monitoring Port.</p></body></html>"))
        self.label_14.setText(_translate("EditDlg", "Q330 Cal Chan:"))
        self.sensBCB.setToolTip(_translate("EditDlg", "Sensor B Model"))
        self.sensBLocLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>Location code for sensor B</p></body></html>"))
        self.sensBLocLE.setPlaceholderText(_translate("EditDlg", "##"))
        self.label_8.setToolTip(_translate("EditDlg", "<html><head/><body><p>Calibration Monitoring Port.</p></body></html>"))
        self.label_8.setText(_translate("EditDlg", "Location Code:"))
        self.sensBPriChnsLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>Primary channels for sensor B</p></body></html>"))
        self.sensBPriChnsLE.setPlaceholderText(_translate("EditDlg", "NCH,ECH,VCH"))
        self.label_9.setToolTip(_translate("EditDlg", "<html><head/><body><p>Calibration Monitoring Port.</p></body></html>"))
        self.label_9.setText(_translate("EditDlg", "Primary Chns:"))
        self.label.setToolTip(_translate("EditDlg", "<html><head/><body><p>Sensor Model.</p></body></html>"))
        self.label.setText(_translate("EditDlg", "Model:"))
        self.label_2.setToolTip(_translate("EditDlg", "<html><head/><body><p>Calibration Monitoring Port.</p></body></html>"))
        self.label_2.setText(_translate("EditDlg", "Q330 Cal Chan:"))
        self.sensAMonPortLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>Calibration monitoring channel for sensor A</p></body></html>"))
        self.sensAMonPortLE.setPlaceholderText(_translate("EditDlg", "[4-6]"))
        self.label_27.setText(_translate("EditDlg", "Sensor A"))
        self.sensACB.setToolTip(_translate("EditDlg", "Sensor A Model"))
        self.sensALocLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>Location code for sensor A</p></body></html>"))
        self.sensALocLE.setPlaceholderText(_translate("EditDlg", "##"))
        self.label_3.setToolTip(_translate("EditDlg", "<html><head/><body><p>Calibration Monitoring Port.</p></body></html>"))
        self.label_3.setText(_translate("EditDlg", "Location Code:"))
        self.sensAPriChnsLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>Primary channels for sensor A</p></body></html>"))
        self.sensAPriChnsLE.setPlaceholderText(_translate("EditDlg", "VCh,NCh,ECh"))
        self.label_4.setToolTip(_translate("EditDlg", "<html><head/><body><p>Calibration Monitoring Port.</p></body></html>"))
        self.label_4.setText(_translate("EditDlg", "Primary Chns:"))
        self.label_26.setText(_translate("EditDlg", "Q330"))
        self.label_5.setToolTip(_translate("EditDlg", "<html><head/><body><p>Three to six (alpha-numeric) character Station Code</p></body></html>"))
        self.label_5.setText(_translate("EditDlg", "Station:"))
        self.staLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>Station Code</p></body></html>"))
        self.staLE.setPlaceholderText(_translate("EditDlg", "STA"))
        self.label_6.setToolTip(_translate("EditDlg", "<html><head/><body><p>IP4 network address used to communicate with this Q330.</p></body></html>"))
        self.label_6.setText(_translate("EditDlg", "IP4 Address:"))
        self.networkLabel.setText(_translate("EditDlg", "Network:"))
        self.netLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>Network Code</p></body></html>"))
        self.netLE.setPlaceholderText(_translate("EditDlg", "NET"))
        self.ipLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>IP4 network address used by this Q330.</p></body></html>"))
        self.ipLE.setPlaceholderText(_translate("EditDlg", "000.000.000.000"))
        self.label_12.setToolTip(_translate("EditDlg", "<html><head/><body><p>Data Port used for calibrating sensors attached to this Q330.</p></body></html>"))
        self.label_12.setText(_translate("EditDlg", "Data Port:"))
        self.dpLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>Data Port used for calibrating sensors attached to this Q330.</p></body></html>"))
        self.dpLE.setPlaceholderText(_translate("EditDlg", "[1-4]"))
        self.snLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>The Kinemetrics internal serial number for this Q330.</p></body></html>"))
        self.snLE.setPlaceholderText(_translate("EditDlg", "0123456789ABCDEF"))
        self.label_11.setToolTip(_translate("EditDlg", "<html><head/><body><p>The Internal Serial Number for this Q330. This can be obtained by ...</p></body></html>"))
        self.label_11.setText(_translate("EditDlg", "Int. SN:"))
        self.tagnoLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>Kinemetric Tag Number for this Q330.</p></body></html>"))
        self.tagnoLE.setPlaceholderText(_translate("EditDlg", "0000"))
        self.label_7.setToolTip(_translate("EditDlg", "<html><head/><body><p>Kinemetric Tag Number for this Q330.</p></body></html>"))
        self.label_7.setText(_translate("EditDlg", "Tag #:"))
        self.label_13.setToolTip(_translate("EditDlg", "<html><head/><body><p>The Auth Code for access to the Data Port used in calibrations. If no auth code is set, this value should be \'0\'.</p></body></html>"))
        self.label_13.setText(_translate("EditDlg", "Data Port Auth Code:"))
        self.dpauthLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>The Auth Code for the Q330 the Data Port</p></body></html>"))
        self.dpauthLE.setPlaceholderText(_translate("EditDlg", "0"))
        self.saveBtn.setText(_translate("EditDlg", "Save"))
        self.cancelBtn.setText(_translate("EditDlg", "Cancel"))
        self.resetBtn.setText(_translate("EditDlg", "Reset"))

