#######################################################################################################################
# Copyright (C) 2016  Regents of the University of California
#
# This is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License (GNU GPL) as published by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GNU General Public License can be found in LICENSE.TXT in the root of the source code repository.
# Additionally, it can be found at http://www.gnu.org/licenses/.
#
# NOTES: Per GNU GPLv3 terms:
#   * This notice must be kept in this source file
#   * Changes to the source must be clearly noted with date & time of change
#
# If you use this software in a product, an explicit acknowledgment in the product documentation of the contribution
# by Project IDA, Institute of Geophysics and Planetary Physics, UCSD would be appreciated but is not required.
#######################################################################################################################
"""Class for in-memory representation of qcal auth file"""

import logging
from config.ical_config_reader import IcalConfigReader
from config.ical_config_writer import IcalConfigWriter
from config.auth import Auth, AuthBadColumnCountExcept, AuthMalformedRecordExcept

class Auths(IcalConfigReader, IcalConfigWriter):

    @classmethod
    def file_header(cls):
        return \
'''################################################################################################################
# etc/auth
# 
# Configuration file for the IDA qcal calibration program.
# It contains, by Tag Number, the Q330 internal serial number and auth codes needed to run calibrations.
#
# !!! DO NOT EDIT THIS FILE MANUALLY UNLESS YOU REALLY REALLY ARE SURE YOU KNOW WHAT YOU'RE DOING !!!
#
#############
#
# The auth file gives the serial numbers and authorization
# codes for each Q330.
#
# It consists of 8 arguments:
#
#  1 - KMI property tag number
#  2 - internal serial number
#  3 - authorization code for configuration port
#  4 - authorization code for special functions port
#  5 - authorization code for data port 1
#  6 - authorization code for data port 2
#  7 - authorization code for data port 3
#  8 - authorization code for data port 4
#
# TagNo  Serial Number     cfg   sfn   dp1   dp2   dp3   dp4
################################################################################################################
'''

    def __init__(self, fpath):
        self.fpath = fpath
        self.items = []
        self.iter_ndx = 0
        self.isdirty = False

        # if file doesn't exist, create it
        super().ensure_file(fpath)

        # read & parse data
        self.parsed_ok = super().parse_cfg_file(self.fpath, self.parse_cfg_records)


    def clear(self):
        self.items = []


    def append(self, rec):
        rec = rec.strip()

        if not (rec.startswith('#') or (len(rec) == 0)):

            try:
                auth = Auth(rec)
            except AuthBadColumnCountExcept:
                logging.warning('Auth record should have at least ' + str(Auth.AUTH_COLCOUNT) + ' columns. [' + rec + ']. Record ignored.')
            except AuthMalformedRecordExcept:
                logging.warning('Auth record appears to be invalid: [' + rec + ']. Record ignored.')
            except Exception as e:
                logging.warning('Unknown error parsing Auth record: [' + rec + ']. Record ignored.' + '\n' + str(e))
            else:
                if next(filter(lambda a: a == auth, self.items), None) == None:
                    self.items.append(auth)
                else:
                    logging.warning('Duplicate Auth record: [' + rec + ']. Record ignored.')


    def sort(self):
        self.items.sort()


    def find(self, key):
        """Returns the first Auth with TAGNO
        If no Auth is found, returns None.
        """
        return next(filter(lambda s: s.data[Auth.AUTH_KEY_TAGNO] == key, self.items), None)


    def __setitem__(self, key, value):
        self.isdirty = True
        pass


    def __delitem__(self, key):
        self.isdirty = True
        pass


