# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditDlg(object):
    def setupUi(self, EditDlg):
        EditDlg.setObjectName("EditDlg")
        EditDlg.resize(672, 340)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditDlg.sizePolicy().hasHeightForWidth())
        EditDlg.setSizePolicy(sizePolicy)
        EditDlg.setMinimumSize(QtCore.QSize(672, 340))
        EditDlg.setMaximumSize(QtCore.QSize(672, 16777215))
        self.buttonBox = QtWidgets.QDialogButtonBox(EditDlg)
        self.buttonBox.setGeometry(QtCore.QRect(315, 297, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(EditDlg)
        self.groupBox.setGeometry(QtCore.QRect(15, 10, 641, 281))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.sensorBGB = QtWidgets.QGroupBox(self.groupBox)
        self.sensorBGB.setGeometry(QtCore.QRect(330, 180, 300, 91))
        self.sensorBGB.setTitle("")
        self.sensorBGB.setObjectName("sensorBGB")
        self.label_28 = QtWidgets.QLabel(self.sensorBGB)
        self.label_28.setGeometry(QtCore.QRect(7, 5, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_10 = QtWidgets.QLabel(self.sensorBGB)
        self.label_10.setGeometry(QtCore.QRect(68, 31, 42, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.sensBMonPortLE = QtWidgets.QLineEdit(self.sensorBGB)
        self.sensBMonPortLE.setGeometry(QtCore.QRect(122, 60, 50, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensBMonPortLE.sizePolicy().hasHeightForWidth())
        self.sensBMonPortLE.setSizePolicy(sizePolicy)
        self.sensBMonPortLE.setMinimumSize(QtCore.QSize(50, 0))
        self.sensBMonPortLE.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.sensBMonPortLE.setFont(font)
        self.sensBMonPortLE.setFrame(False)
        self.sensBMonPortLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.sensBMonPortLE.setObjectName("sensBMonPortLE")
        self.label_14 = QtWidgets.QLabel(self.sensorBGB)
        self.label_14.setGeometry(QtCore.QRect(15, 61, 95, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(95, 0))
        self.label_14.setMaximumSize(QtCore.QSize(95, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.sensACB_2 = QtWidgets.QComboBox(self.sensorBGB)
        self.sensACB_2.setGeometry(QtCore.QRect(117, 27, 170, 26))
        self.sensACB_2.setObjectName("sensACB_2")
        self.sensorAGB = QtWidgets.QGroupBox(self.groupBox)
        self.sensorAGB.setGeometry(QtCore.QRect(330, 40, 300, 91))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sensorAGB.setFont(font)
        self.sensorAGB.setTitle("")
        self.sensorAGB.setObjectName("sensorAGB")
        self.label = QtWidgets.QLabel(self.sensorAGB)
        self.label.setGeometry(QtCore.QRect(68, 31, 42, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.sensorAGB)
        self.label_2.setGeometry(QtCore.QRect(15, 61, 95, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(95, 0))
        self.label_2.setMaximumSize(QtCore.QSize(95, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.sensAMonPortLE = QtWidgets.QLineEdit(self.sensorAGB)
        self.sensAMonPortLE.setGeometry(QtCore.QRect(122, 60, 50, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensAMonPortLE.sizePolicy().hasHeightForWidth())
        self.sensAMonPortLE.setSizePolicy(sizePolicy)
        self.sensAMonPortLE.setMinimumSize(QtCore.QSize(50, 0))
        self.sensAMonPortLE.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.sensAMonPortLE.setFont(font)
        self.sensAMonPortLE.setFrame(False)
        self.sensAMonPortLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.sensAMonPortLE.setObjectName("sensAMonPortLE")
        self.label_27 = QtWidgets.QLabel(self.sensorAGB)
        self.label_27.setGeometry(QtCore.QRect(7, 5, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.sensACB = QtWidgets.QComboBox(self.sensorAGB)
        self.sensACB.setGeometry(QtCore.QRect(117, 27, 170, 26))
        self.sensACB.setObjectName("sensACB")
        self.q330GB = QtWidgets.QGroupBox(self.groupBox)
        self.q330GB.setGeometry(QtCore.QRect(10, 40, 310, 231))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.q330GB.setFont(font)
        self.q330GB.setTitle("")
        self.q330GB.setObjectName("q330GB")
        self.label_26 = QtWidgets.QLabel(self.q330GB)
        self.label_26.setGeometry(QtCore.QRect(9, 5, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.layoutWidget = QtWidgets.QWidget(self.q330GB)
        self.layoutWidget.setGeometry(QtCore.QRect(6, 30, 295, 188))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setObjectName("formLayout")
        self.networkLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.networkLabel.setFont(font)
        self.networkLabel.setObjectName("networkLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.networkLabel)
        self.netLE = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.netLE.sizePolicy().hasHeightForWidth())
        self.netLE.setSizePolicy(sizePolicy)
        self.netLE.setMinimumSize(QtCore.QSize(60, 0))
        self.netLE.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.netLE.setFont(font)
        self.netLE.setFrame(False)
        self.netLE.setObjectName("netLE")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.netLE)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.staLE = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.staLE.sizePolicy().hasHeightForWidth())
        self.staLE.setSizePolicy(sizePolicy)
        self.staLE.setMinimumSize(QtCore.QSize(60, 0))
        self.staLE.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.staLE.setFont(font)
        self.staLE.setFrame(False)
        self.staLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.staLE.setObjectName("staLE")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.staLE)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.ipLE = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ipLE.sizePolicy().hasHeightForWidth())
        self.ipLE.setSizePolicy(sizePolicy)
        self.ipLE.setMinimumSize(QtCore.QSize(145, 0))
        self.ipLE.setMaximumSize(QtCore.QSize(145, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ipLE.setFont(font)
        self.ipLE.setFrame(False)
        self.ipLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.ipLE.setObjectName("ipLE")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ipLE)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.tagnoLE = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagnoLE.sizePolicy().hasHeightForWidth())
        self.tagnoLE.setSizePolicy(sizePolicy)
        self.tagnoLE.setMinimumSize(QtCore.QSize(60, 0))
        self.tagnoLE.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tagnoLE.setFont(font)
        self.tagnoLE.setFrame(False)
        self.tagnoLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.tagnoLE.setObjectName("tagnoLE")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tagnoLE)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.snLE = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snLE.sizePolicy().hasHeightForWidth())
        self.snLE.setSizePolicy(sizePolicy)
        self.snLE.setMinimumSize(QtCore.QSize(145, 0))
        self.snLE.setMaximumSize(QtCore.QSize(145, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.snLE.setFont(font)
        self.snLE.setFrame(False)
        self.snLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.snLE.setObjectName("snLE")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.snLE)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.dpLE = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpLE.sizePolicy().hasHeightForWidth())
        self.dpLE.setSizePolicy(sizePolicy)
        self.dpLE.setMinimumSize(QtCore.QSize(60, 0))
        self.dpLE.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.dpLE.setFont(font)
        self.dpLE.setText("")
        self.dpLE.setFrame(False)
        self.dpLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.dpLE.setObjectName("dpLE")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dpLE)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.dpauthLE = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpauthLE.sizePolicy().hasHeightForWidth())
        self.dpauthLE.setSizePolicy(sizePolicy)
        self.dpauthLE.setMinimumSize(QtCore.QSize(60, 0))
        self.dpauthLE.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.dpauthLE.setFont(font)
        self.dpauthLE.setFrame(False)
        self.dpauthLE.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.dpauthLE.setObjectName("dpauthLE")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.dpauthLE)

        self.retranslateUi(EditDlg)
        self.buttonBox.accepted.connect(EditDlg.accept)
        self.buttonBox.rejected.connect(EditDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(EditDlg)

    def retranslateUi(self, EditDlg):
        _translate = QtCore.QCoreApplication.translate
        EditDlg.setWindowTitle(_translate("EditDlg", "Dialog"))
        self.groupBox.setTitle(_translate("EditDlg", "Edit Calibration Configuration"))
        self.label_28.setText(_translate("EditDlg", "Sensor B"))
        self.label_10.setToolTip(_translate("EditDlg", "<html><head/><body><p>Sensor Model.</p></body></html>"))
        self.label_10.setText(_translate("EditDlg", "Model:"))
        self.sensBMonPortLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>Calibration Monitoring Port.</p></body></html>"))
        self.sensBMonPortLE.setPlaceholderText(_translate("EditDlg", "[1-3]"))
        self.label_14.setToolTip(_translate("EditDlg", "<html><head/><body><p>Calibration Monitoring Port.</p></body></html>"))
        self.label_14.setText(_translate("EditDlg", "Calib Mon Port:"))
        self.label.setToolTip(_translate("EditDlg", "<html><head/><body><p>Sensor Model.</p></body></html>"))
        self.label.setText(_translate("EditDlg", "Model:"))
        self.label_2.setToolTip(_translate("EditDlg", "<html><head/><body><p>Calibration Monitoring Port.</p></body></html>"))
        self.label_2.setText(_translate("EditDlg", "Calib Mon Port:"))
        self.sensAMonPortLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>Calibration Monitoring Port.</p></body></html>"))
        self.sensAMonPortLE.setPlaceholderText(_translate("EditDlg", "[4-6]"))
        self.label_27.setText(_translate("EditDlg", "Sensor A"))
        self.label_26.setText(_translate("EditDlg", "Q330"))
        self.networkLabel.setText(_translate("EditDlg", "Network"))
        self.netLE.setPlaceholderText(_translate("EditDlg", "NET"))
        self.label_5.setToolTip(_translate("EditDlg", "<html><head/><body><p>Three to six (alpha-numeric) character Station Code</p></body></html>"))
        self.label_5.setText(_translate("EditDlg", "Station:"))
        self.staLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>Three to six (alpha-numeric) character Station Code</p></body></html>"))
        self.staLE.setPlaceholderText(_translate("EditDlg", "STA"))
        self.label_6.setToolTip(_translate("EditDlg", "<html><head/><body><p>IP4 network address used to communicate with this Q330.</p></body></html>"))
        self.label_6.setText(_translate("EditDlg", "IP4 Address:"))
        self.ipLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>IP4 network address used to communicate with this Q330.</p></body></html>"))
        self.ipLE.setPlaceholderText(_translate("EditDlg", "000.000.000.000"))
        self.label_7.setToolTip(_translate("EditDlg", "<html><head/><body><p>Kinemetric Tag Number for this Q330.</p></body></html>"))
        self.label_7.setText(_translate("EditDlg", "Tag #:"))
        self.tagnoLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>Kinemetric Tag Number for this Q330.</p></body></html>"))
        self.tagnoLE.setPlaceholderText(_translate("EditDlg", "0000"))
        self.label_11.setToolTip(_translate("EditDlg", "<html><head/><body><p>The Internal Serial Number for this Q330. This can be obtained by ...</p></body></html>"))
        self.label_11.setText(_translate("EditDlg", "Int. SN:"))
        self.snLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>The Internal Serial Number for this Q330. This can be obtained by ...</p></body></html>"))
        self.snLE.setPlaceholderText(_translate("EditDlg", "0123456789ABCDEF"))
        self.label_12.setToolTip(_translate("EditDlg", "<html><head/><body><p>Data Port used for calibrating sensors attached to this Q330.</p></body></html>"))
        self.label_12.setText(_translate("EditDlg", "Data Port:"))
        self.dpLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>Data Port used for calibrating sensors attached to this Q330.</p></body></html>"))
        self.dpLE.setPlaceholderText(_translate("EditDlg", "[1-4]"))
        self.label_13.setToolTip(_translate("EditDlg", "<html><head/><body><p>The Auth Code for access to the Data Port used in calibrations. If no auth code is set, this value should be \'0\'.</p></body></html>"))
        self.label_13.setText(_translate("EditDlg", "Data Port Auth Code:"))
        self.dpauthLE.setToolTip(_translate("EditDlg", "<html><head/><body><p>The Auth Code for access to the Data Port used in calibrations. If no auth code is set, this value should be \'0\'.</p></body></html>"))
        self.dpauthLE.setPlaceholderText(_translate("EditDlg", "0"))

